- docker.te
From: Dan Walsh <dwalsh@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>
> resolve syntax error

- docker.te
From: Dan Walsh <dwalsh@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>
@rhatdan @wrabcak PTAL
> Resolves: rhbz#1318360 - delete bounds checking rules

- container.te
Backport of:
https://github.com/projectatomic/container-selinux/pull/36
> Allow sandbox containers manage fuse files.

- container.fc
Closes: https://github.com/projectatomic/atomic/issues/1176
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> container.fc: label system containers /exports as container_config_t

- container.if
> Add container_manage_config_files() interface

- container.fc
Partially addresses:
https://github.com/coreos/fedora-coreos-tracker/issues/42
> container.fc: label {var/srv,srv}/containers as container_file_t

- README.md
As per title.
Signed-off-by: Ashley Cui <ashleycui16@gmail.com>
> SELinux policy documentation in README

- container.fc
> Add /usr/local/bin/docker.*

- NOTICE
@rhatdan Could you please review and process the PR for adding the NOTICE file.
> Added Copyright Notice file

- container.te
> Add nfs remount support

- container.te
> Allow unconfined domains to talk to unlabled sockets

- container.te
> Allow spc_t domains to set bpf rules on any domain

- README.md
The projectatomic.io links don't seem to work anymore.
Signed-off-by: Craig Jellick <craig@rancher.com>
> Remove broken links from README.md

- README.md
Fixed error on line 6 with error in container_var_lib_t annotation.
> Updated typo in README

- container.te
Remove legacy noxattrfs association from container_file_t.
> Remove noxattrfs from container_file_t

- container.fc
- container.if
- container_selinux.8
Tested with BuildKit v0.10.5 on Fedora 36.
Fix #187
> Support BuildKit

- container.fc
Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>
> support nerdctl

- .packit.yaml
- Makefile
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
> Makefile: install.udica-templates target

- rpm/container-selinux.spec
Original ref: https://src.fedoraproject.org/rpms/container-selinux/pull-request/7#
From: Nikola Knazekova <nknazeko@redhat.com>
Adding upstream first since we're switching to a packit workflow for downstream tasks.
@rhatdan PTAL
> RPM: own files created in post install

- rpm/container-selinux.spec
Related to https://github.com/packit/packit/issues/1974.
> Fix conditionalized %changelog content

- rpm/container-selinux.spec
> Fix user_namespace support detection

- .packit.yaml
@TomSweeneyRedHat @rhatdan PTAL
> Packit: use @containers/packit-build team for copr failure notification comments

- container.if
- container.te
Fixes: https://github.com/containers/container-selinux/issues/283
> Fix kubernetes transition rule

- container.te
in the reviews some things were missed
> improve container_engine_t

- plans/main.fmf
@edsantiago said specifying the podman binary path in system tests is not correct usage.
> tmt: run podman system tests correctly

- container.te
after running podman system tests inside of a container
> extend container_engine_t again
