containers/container-selinux

docker.te

From: Dan Walsh <dwalsh@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>
(cherry picked from commit 60e4b7ce2c80b2bded12938f5b00e85c6f661185)
@rhatdan rhel builds fail without this. ptal

resolve syntax error

---

docker.fc

Cherry-pick/backport of #7.
This is related to docker/docker#21672 and docker/docker#21673.
Signed-off-by: Eli Young <elyscape@gmail.com>
(cherry picked from commit 47561ec90ac9fff6430baa2e93e183963dcf3a1c)

Add label for Docker log files

---

container.fc
container.if
container.te

Since this policy is controlling the containers runtimes, not the containers.
I would rather save container_t for the name of the processes running in the
container.

Names should be changed to container_runtime instead of just container

---

container.fc
container.te

Create directories under /var/lib/docker* with the correct label.
@rhatdan just cherry-picked your latest master commit to RHEL-1.12

Fix labeling for docker-latest

---

container-selinux.spec

There is no %{repo} global defined anymore in this spec.
This is most likely the cause for https://github.com/CentOS/sig-atomic-buildscripts/issues/224 -- i.e. the docker module from `selinux-policy-targeted` is never actually disabled, which meant that installation was failing. I say might, because I haven't been able to actually build a `container-selinux` package with the fix yet for various reasons. The fix looks right though.

drop bad references to %{repo}

---

container.te

Unprivileged containers cannot currently access XFRM sockets. This is causing issues for Rancher users running on RHEL or CentOS with SELinux enabled due to Rancher's IPsec network implementation.
Unfortunately I'm not familiar enough with SELinux to determine whether unprivileged containers should have these permissions in general. I see the same permissions on similar socket types so it doesn't seem too unreasonable, but I'm still interested to hear feedback on this.
cc @ibuildthecloud

Give container_t access to XFRM sockets

---

container.fc

LXD adds a few paths over LXC, but otherwise should work fine with the current policy.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>

Add support for LXD

---

container.fc

Now that containerd is packaged as a standalone project, include the paths where
it is installed for SELinux.
Note that currently, until runc reaches 1.0, the containerd packaging includes
runc, and it is packaged in `/usr/sbin`, so add this path too.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Add containerd paths

---

container.te

I see these denials if create SELinux policy using udica tool. It should be dontaudited. 
Found by: @janzarsky
PTAL: @rhatdan

Dontaudit containers to request limits and signal state from container engine.

---

container.if

Fix require of wrong SELinux label in container_manage_config_files from
container_var_lib_t to container_config_t.

Fix typo in container_manage_config_files()

---

container.te

This PR allows containers to use [Onload](http://www.openonload.org/) files.  The two commits address two distinct problems:
1. Permission was already granted in 132fee4 to `container_runtime_t`, but not to `container_t` itself.
1. The implementation of `fs_rw_onload_sockets()` in `selinux-policy` grants permissions only to the `sock_file` class, but `file` and `fifo_file` are also necessary.  There is a PR with a proposed fix at https://github.com/fedora-selinux/selinux-policy/pull/251, but in the meantime, there is a commit in the current PR that overrides `fs_rw_onload_sockets()` with a fixed implementation.  Overriding in this manner is a touch unsavoury, so if it would be preferred, I could rewrite the patch to introduce a new interface rather than overriding the old one.

Allow containers to use onloadfs files

---

container.fc

set the label for crun to system_u:object_r:container_runtime_exec_t.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

container.fc: label crun

---

container.te

Referencing container_ro_file_t which was already declared in virt.te.

Change container_ro_file_t type statement to typealias

---

contrib/container-selinux.spec

Change the uninstall command in the %postun section of the specfile
to use the %selinux_modules_uninstall macro which uses priority 200.
Change formatting so that the lines are vertically aligned
in the %postun section.

Use priority 200 for uninstalling the module BZ(1777740)

---

container.te

container_filetrans_named_content macro is called by
named_filetrans_domain attribute to ensure that multiple SELinux domains can create objects on file system with correct SELinux label. This part of policy should be in container-selinux because container types are defined in container-selinux not selinux-policy package.
Relate to: https://github.com/fedora-selinux/selinux-policy/commit/50a6afe26d1b3083c339adc1c5f6193ec0cb71cd

Drop some container interface from selinux-policy

---

container.fc
container.if

Adapts changes suggested by @crosbymichael:
- https://github.com/containerd/cri/pull/1246#issuecomment-629279591
Unsure if this works because #97. Any pointers to resolve the installation issue would be greatly appreciated.

support containerd/cri

---

container.te

Fixes #104 - Containers that run processes which open /dev/net/tun and attempt to use an existing named network device in their network namespace (e.g. Qemu) need relabelto/relabelfrom on tun_socket. This is important for use cases where we don't want containers to have NET_ADMIN but still want them to be able to use tap devices that are pre-created for the container.
I'm not sure if this is the ideal fix, but this seems like a good way to get the discussion going if there is a different way. I did check fedora-selinux to see if there were any existing booleans, rules, or interfaces that could be called.
When a userspace process opens /dev/net/tun and attempts to open a tun/tap device by calling ioctl [TUNSETIFF](https://github.com/torvalds/linux/blob/1127b219ce9481c84edad9711626d856127d5e …

Allow container_t to open existing tun/tap

---

container.te

Fixes cases where the runtime/CNI has created new tap devices as container_runtime_t
```
type=AVC msg=audit(1605647505.495:3870204537): avc:  denied  { relabelfrom } for
pid=3716920 comm="qemu-system-x86" scontext=system_u:system_r:container_t:s0:c484,c585
tcontext=system_u:system_r:container_runtime_t:s0 tclass=tun_socket permissive=0
```
This occurred during a change of our container runtime and CNI, it was found that the tap devices being
created by CNI were inheriting container_runtime_t. These are for the private kernel sockets that represent
the actual tap devices, not the /dev/net/tun interface.
I tried playing with type transitions to see if we could get the private kernel sockets to transition to container_t,
but I couldn't quite work out what the target type was for these …

Allow container to relabel tun/tap device from container_runtime_t

---

container.te

Allow init containers to send syslog messages

---

container.if

The container_filetrans_named_content macro calls out to the
files_pid_filetrans macro for the "kata-containers" dir passing a type
missing from the gen_require stanza. This is causing my downstream
builds of rke2-selinux to fail (current work-around is to require
container_kvm_var_run_t in our rke2_filetrans_named_content macro).
Signed-off-by: Jacob Blain Christen <jacob@rancher.com>

adjust container_filetrans_named_content gen_require

---

container.te

The given object is later referenced by name anyway, so using those is
no better than using gen_require() directly. We would like to remove
these stub interfaces from selinux-policy.

Drop use of "stub" interfaces

---

container.te

Since non privileged users are able to write to /dev/random and
/dev/urandom, I see no reason to block this with SELinux.
Running systemd inside of a rootless container requires this.

Allow containers to write to /dev/rand, /dev/urand

---

container.te

In commit 4c51e97504d ("Allow spc_t domains to set bpf rules on any domain"),
a comment is introduced with double-slash symbol which is not
considered valid in policy sources.
Addresses the following problem:
/usr/bin/checkmodule -m tmp/container.tmp -o tmp/container.mod
policy/modules/contrib/container.te:667:ERROR 'syntax error' at token '//' on line 25264:
// This should eventually be in upstream policy.
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [Rules.modular:77: tmp/container.mod] Error 1
rm tmp/container.mod.fc
Error: Process completed with exit code 2.

Replace "//" with "#"

---

container.fc

This integrates SELinux policy rules from the [k3s-selinux package](https://github.com/k3s-io/k3s-selinux)
so that k3s works on SELinux out of the box.

Add support for k3s

---

container.te

Also allow container_domains to use inherited unix_stream_sockets from
userdomains.
Fixes: https://github.com/containers/container-selinux/issues/147

Allow iptables to use fifo files of a container runtime

---

container.fc

- Addresses part of k3s-io/k3s#4401
- Transitions located at k3s-io/k3s-selinux#25
Signed-off-by: Jacob Blain Christen <jacob@rancher.com>

some entries under the k3s data-dir should not be container_runtime_exec_t

---

container.fc

K3s brings its own embedded userland runtime and dumps it on disk under
/var/lib/rancher/k3s/data/${content_id=-"current"}/ which includes runc,
containerd, and the containerd shims. The initial k3s policy implementation
re-used existing policy types from container-selinux and marked all of
the disgorged userland (binaries and config, alike) as
container_runtime_exec_t which is what runc and the containerd bits
require. Because we ship busybox in this userland, with the shell
applet, this can lead to elevated privileges for any unconfined seuser
(the default for unmodified installations).
To address this problem we have re-written the k3s-selinux policy to
declare and leverage a couple of custom types for the various bits of
"content" that k3s brings. As such, the k3s-specific …

remove k3s fcontexts

---

container.if

The container_runtime_run() interface does not contain the dbus class
declaration which under some conditions makes the interface not compile:
$ sepolicy interface -c -i container_runtime_run
Compiling container_runtime_run interface
Compiling targeted compiletest module
compiletest.te:43:ERROR 'unknown class dbus' at token ';' on line 4492:
allow sepolicy_domain_t container_runtime_t:dbus send_msg;
#line 43
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [/usr/share/selinux/devel/include/Makefile:157: tmp/compiletest.mod] Error 1
Compile test for container_runtime_run failed.
Resolves: rhbz#1967642

Add missing dbus class declaration into container_runtime_run()

---

container.fc

Kubelet is misspelled, so /var/lib/kubelet is not properly labeled by this policy.

Update file labeling type for /var/lib/kubelet

---

container.fc
container.te

Assign the conmon executable a private type and explicitly add a ranged
transition such that podman runs conmon in s0.
This is a companion PR to https://github.com/containers/podman/pull/13093
Fixes: #152

Add explicit range transition for conmon

---

container.fc

Set the label for `kata-agent` to `system_u:object_r:container_runtime_exec_t` because Kata Containers will start supporting for SELinux on the guest side.
`kata-agent` spawns and runs containers inside Kata VM, so it behaves like a general container runtime. To enable SELinux on the Kata VM, `kata-agent` should be labeled as `container_runtime_exec_t`.
Ref. https://github.com/kata-containers/kata-containers/pull/4813
Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

container.fc: Set label for kata-agent

---

container.te

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
The policy is needed for Passt, see [passt.te](https://passt.top/passt/tree/contrib/selinux/passt.te#n82)
for reference.

Allow containers to mount tmpfs_t file systems

---

container.te

Allow spc_t to use timedatectl
Signed-off-by: Johannes Segitz <jsegitz@suse.de>

Allow spc_t to use timedatectl

---

container.te

Allow spc_t to use localectl
Signed-off-by: Johannes Segitz <jsegitz@suse.de>

Allow spc_t to use localectl

---

container.te

With the 018cb36d55 ("Allow spc_t to transption to rpm_script_t") commit, spc_t was allowed to transition to the rpm_script_t domain. The interface, however, requires 2 arguments, the second one being role allowed access.

Add system_r role to rpm_transition_script(spc_t)

---

container.te

@rhatdan PTAL
v2.202.0 does not build on fedora.  Need a new version with the fix in https://github.com/containers/container-selinux/pull/206

bump to v2.203.0

---

container.te

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2177273

Allow containers to watch sysfs_t directories

---

container-selinux.spec.rpkg

Also, user_namespace is only present on fedora > 37. Skip it for rhel <= 9.

Packit: fix rhel 8 builds

---

container.fc

The kubernetes local-path-provisioner uses either
/opt/local-path-provisioner or
/var/local-path-provisioner for its physical volumes

set default context for local-path-provisioner

---

.packit.yaml

This should (probably) unblock the `trigger:commit` builds as well.
Limit the testing targets to x86_64 only.

Packit: Explicitly specify all targets

---

container.if
container.te

When users run dbus based applications as containers, they expect other processes to dbus chat with them.  I don't want to allow all domains to dbus chat since this would include container_t. Allowing daemon, will allow the bulk of confined domains to interact with spc_t.

Allow daemon to send dbus messages to spc_t

---

.packit.sh
.packit.yaml
rpm/container-selinux.spec
rpm/update-spec-version.sh

Packit: add jobs for downstream Fedora package builds

---

.packit.sh
rpm/container-selinux.spec

A prior merge of 5802ca2b007a067703c25b366aa9d29a8fd491f3
undid some changes for the `install.selinux-user` target in rpm/spec.
This commit also fixes that.

Packit: fix build issues

---

container.te

Podman container checkpoint/restore needs to be able to dyntrans from container_runtime_t to spc_t.

Allow container runtime to dyntransition to spc_t

---

container.te

Certain users want to volume mount /etc/pki and friends into a container but still run locked down.

Add boolean to allow containers to read all cert files

---

rpm/container-selinux.spec

bcond_with/out macros are hard for the human to read and are often confused. The `define` macros are much easier.
Also remove the git0 macro as it's no longer needed.

rpm: replace bcond_ macros with define

---

container.fc

or else it will be labeled unconfined_service_t, as it's by default a bin_t, and systemd is executing it
fixes https://issues.redhat.com/browse/OCPBUGS-20022

label kubenswrapper kubelet_exec_t

---

.packit.yaml
plans/main.fmf

This commit enables podman system and e2e tests for CentOS Stream and
RHEL, both 8 and 9.
The rhel tests run on the internal testing farm and have an `internal`
suffix appended for clarity. Only people with
access to the internal redhat network can access the logs.

Packit/TMT: enable CentOS Stream, RHEL [8,9] tests

---

container.fc

from the kubelet's perspective, this endpoint is read only--a process cannot change anything in the kubelet by accessing it.
Since access to these files will be prevented by kubernetes security policy (eliminating the vector of malicious snooping), I think it will be safe to allow containers rw access to this socket.
Fixes https://issues.redhat.com/browse/RHEL-3128

give containers access to pod resources endpoint

---

container.te

Fixes: https://github.com/containers/container-selinux/issues/274

Allow container domains to execute container_runtime_tmpfs_t files

---

container.fc

on openshift, kubenswrapper service calls kubensenter, which calls the kubelet. Without this change, kubelet will continue to be labeled unconfined_t

label kubensenter as well as kubenswrapper

---

container.te

BPF Filesystems (bpffs) are used to manage BPF Object Lifecycles. For example, you can place a special object (called a pin) on a BPF filesystem and use that object to get a reference to the program/link/map that it references if you have permissions to make bpf() syscalls.
In a recent kernel patch, a container may also recieve a token that allows it to make BPF syscalls on this filesystem.
Since bpffs doesn't support xattrs, it's not possible to bind mount it from the host with `:Z` so it can be re-labelled. Adding xattrs to bpffs is not something that I've looked into in detail, but I imagine it's non-trivial.
This commit should add the necessary rules to ensure that SELinux permits the use of bpf_t file/directory objects from containers when the BPFFS volume was bind mounted from the …

Allow access to BPF Filesystems

---

container.te

Fixes: https://github.com/containers/container-selinux/issues/269

Default to allowing containers to use dri devices

---

container.te

I imagine more pieces will be needed, but these changes allowed me to create a rootless container within an unprivileged pod

container_engine_t: improve for podman in kubernetes case

---

container.te

Fixes: most of https://github.com/containers/container-selinux/issues/293

Additional rules for container_user_t

---

.packit.yaml
plans/main.fmf
plans/podman_e2e_test.sh
plans/podman_system_test.sh
plans/prepare.sh

This commit also reorganizes individual tests in scripts so they can be executed standalone if need be.
The RHEL targets are also updated to use more generic floating targets wherever possible.

TMT: reorganize tests into scripts

---

.packit.yaml
plans/main.fmf
rpm/container-selinux.spec

This commit enables downstream syncing to CentOS Stream 10. This isn't fully automated yet and requires the maintainer to run `packit propse-downstream` and `centpkg build` steps manually.
This commit also adds TMT podman revdep tests for CentOS Stream 10 and RHEL 10 Beta Nightly. These tests are likely to fail pending netavark work to default to nftables.
This commit will also run separate jobs for `epel-9` and `centos-stream-9` to ensure we're using rhel rpms for rhel tests and centos stream rpms for centos stream tests. This will also be done for centos stream 10 / rhel 10 once the epel-10 target is created on copr.

Packit/TMT: enable downstream syncing to CentOS Stream 10

---

container.te

Using GPUs to accelerate workloads requires the permissions guarded by container_use_xserver_devices. By default it's disabled

introduce container_use_xserver_devices boolean to allow GPU access

---

.packit.yaml

`update_release` is useless in downstream. FWIW, it's also not desirable for upstream / copr jobs.

Packit: remove `update_release` key from downstream jobs

---

.packit.yaml
plans/all.fmf
test/Makefile
test/main.fmf
test/podman-tests.sh

This commit moves a lot of the copr and epel repo enablement in the test environment from shell script to idiomatic packit.

TMT: Simplify tests

---

rpm/container-selinux.spec

All of Fedora and CentOS Stream 10 have autochangelog support so we don't need the changelog conditionals.

RPM: cleanup changelog

---

.packit.yaml

This commit removes f39 from the copr jobs and disables el9 podman revdep test jobs as we recently disabled f39 and el9 jobs on the podman-next copr due to golang 1.22 bump for our golang projects.
The copr and dist-git targets are also reused with yaml anchors wherever possible.

Packit: update targets

---

container.te

For some apps running under docker, docker attempts emulation mode triggering this AVC.
No reason to now allow it.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2297712

dontaudit spc_t to mmap_zero

---

container.fc
container.if

No type was being set for this directory so it ended up inheriting the type for /var/log causing testing failures in microshift environments on upgrade from rhel 9.3 to 9.4.

set container_log_t type for /var/log/kube-apiserver

---

rpm/container-selinux.spec

Helps fix: https://github.com/containers/container-selinux/discussions/331

container-selinux install on non selinux-policy-targeted systems

---

rpm/container-selinux.spec
test/Makefile

Wildcarding filepath in rpm files list doesn't seem to work as expected. This commit replaces wildcarded path with the exact path and also skips mode verification of the files installed in the ghosted path.
Also included is a test to check for file ownership in /var/lib/selinux.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2308833

RPM: explicitly list ghosted paths and skip mode verification

---

container.te
rpm/container-selinux.spec

manpage ownership no longer conflicts with selinux-policy.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2282098
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2209120

rpm: ship manpage

---

container.fc
container.te

This reverts commit 0c0056ffd8e890673ea4b48df12be111905908ff for the `rhaos-maint` branch. This branch will be consumed by rhaos 4.16 and 4.17 for now.

[rhaos-maint] Revert "Allow kubelet_t to create a sock file kubelet_var_lib_t"
